version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: efpp-postgres
    environment:
      POSTGRES_DB: efpp
      POSTGRES_USER: efpp_user
      POSTGRES_PASSWORD: efpp_password
    ports:
      - "5432:5432"
